# Generated by Django 5.2.12 on 2026-03-27

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _build_title(text):
    normalized = " ".join((text or "").split())
    if not normalized:
        return "New chat"
    if len(normalized) <= 80:
        return normalized
    return f"{normalized[:77].rstrip()}..."


def migrate_legacy_history(apps, schema_editor):
    ChatHistory = apps.get_model("chat", "ChatHistory")
    ChatConversation = apps.get_model("chat", "ChatConversation")
    ChatTurn = apps.get_model("chat", "ChatTurn")

    for entry in ChatHistory.objects.all().iterator():
        conversation = ChatConversation.objects.create(
            id=uuid.uuid4(),
            user_id=entry.user_id,
            title=_build_title(entry.query),
            last_message_preview=_build_title(entry.query),
        )
        ChatConversation.objects.filter(pk=conversation.pk).update(
            created_at=entry.created_at,
            updated_at=entry.created_at,
        )

        turn = ChatTurn.objects.create(
            conversation_id=conversation.pk,
            query=entry.query,
            response=entry.response,
            documents=[],
        )
        ChatTurn.objects.filter(pk=turn.pk).update(created_at=entry.created_at)


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatConversation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("last_message_preview", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="chat_conversations", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatTurn",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("query", models.TextField()),
                ("response", models.TextField()),
                ("documents", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("conversation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="turns", to="chat.chatconversation")),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.RunPython(migrate_legacy_history, migrations.RunPython.noop),
    ]
